# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 2

Vagrant.configure(2) do |config|

  #virtualbox  settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1096"
  end


  NODE_COUNT.times do |i|

    node_id = "node#{i}"
    config.ssh.insert_key = true
        
    config.vm.define node_id do |node|
      node.vm.box = "ubuntu/precise64"
      node.vm.box_check_update = false
      node.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.20#{i}"
      node.vm.hostname = "hadoopnode#{i}"

      #setup hosts file
      node.vm.provision "shell", inline: " echo \"127.0.0.1 localhost\" > /etc/hosts "
      NODE_COUNT.times do |j|
        node.vm.provision "shell", inline: " echo \"192.168.1.20#{j}  hadoopnode#{j}.gunawardena.id.au  hadoopnode#{j}\" >> /etc/hosts "
      end

    end 
  end
end


#ssh-keygen

# sudo fallocate -l 2G /swapfile
# sudo chmod 600 /swapfile
# sudo mkswap /swapfile
# sudo swapon /swapfile


# cd /etc/apt/sources.list.d
# wget http://public-repo-1.hortonworks.com/ambari/ubuntu12/1.x/updates/1.7.0/ambari.list

# apt-key adv --recv-keys --keyserver keyserver.ubuntu.com B9733A7A07513CAD
# apt-get update
# apt-get install ambari-server


# ambari-server setup
# ambari-server start


# http://192.168.1.200:8080.







