---
- hosts: all
  remote_user: vagrant  
  sudo: true

  tasks:

    - unarchive: src=hbase-1.0.0-bin.tar.gz dest=/usr/local/ owner=hduser group=hadoop mode="u=rwx,g=rwx,o=r" 
    - command: creates="/usr/local/hbase" mv /usr/local/hbase-1.0.0 /usr/local/hbase
    - file: path=/usr/local/hbase owner=hduser group=hadoop mode="u=rwx,g=rwx,o=r" recurse=yes
    - copy: src=hbase_conf_files/hbase-site.xml dest=/usr/local/hbase/conf/hbase-site.xml  owner=hduser group=hadoop mode="u=rwx,g=rwx,o=r"

    - shell: echo "node1" > /usr/local/hbase/conf/regionservers
      sudo_user: hduser

    - shell: echo "\nexport JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64\n" >> /usr/local/hbase/conf/hbase-env.sh
      sudo_user: hduser


# /usr/local/hadoop/bin/hadoop namenode -format
# start-dfs.sh
# start-mapred.sh 
# /usr/local/hbase/bin/start-hbase.sh
# /usr/local/hbase/bin/stop-hbase.sh

# tail -f /usr/local/hbase/logs/hbase-hduser-zookeeper-node0.log


# /usr/local/hbase/bin/hbase shell

# create 'test', 'ab'

# /usr/local/hbase/conf/regionservers