---
- hosts: all
  remote_user: vagrant  
  sudo: true

  tasks:

    - copy: src=hbase_conf_files/hbase-site.xml dest=/usr/local/hbase/conf/hbase-site.xml  owner=hduser group=hadoop mode="u=rwx,g=rwx,o=r"

    - shell: echo "node0" > /usr/local/hbase/conf/regionservers
      sudo_user: hduser

    - shell: echo "\nexport JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64\n" >> /usr/local/hbase/conf/hbase-env.sh
      sudo_user: hduser



# start-dfs.sh
# /usr/local/hbase/bin/start-hbase.sh
# /usr/local/hbase/bin/stop-hbase.sh

# tail -f /usr/local/hbase/logs/hbase-hduser-zookeeper-node0.log


# /usr/local/hbase/bin/hbase shell

# create 'test', 'ab'

