# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 2

Vagrant.configure(2) do |config|

	#virtualbox  settings
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
	end


  NODE_COUNT.times do |i|

		node_id = "node#{i}"

		config.vm.define node_id do |node|
			node.vm.box = "ubuntu/trusty64"
			node.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "10.1.1.10#{i}"
			node.vm.hostname = "#{node_id}.intranet.local"

			#create user
			config.vm.provision "shell", inline: 'adduser hduser --gecos "Hadoop user,,," --disabled-password'

			#create .ssh folder
			config.vm.provision "shell", inline: 'mkdir -p /home/hduser/.ssh'
			config.vm.provision "shell", inline: 'chmod a+w /home/hduser/.ssh'
			config.vm.provision "shell", inline: 'chown hduser /home/hduser/.ssh'

			#if master copy private key
			if i == 0
				config.vm.provision "file", source: "keys/id_rsa", destination: "/home/hduser/.ssh/id_rsa"
			end

			#copy public key for all
			#config.vm.provision "file", source: "keys/id_rsa.pub", destination: "/home/hduser/.ssh/id_rsa.pub"

			#fix permissions


		end	

  end

end
