# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 2

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  NODE_COUNT.times do |i|
    node_id = "node#{i}"
    config.vm.define node_id do |node|
	    node.vm.box = "ubuntu/trusty64"
	    node.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "10.1.1.10#{i}"
	    node.vm.hostname = "#{node_id}.intranet.local"
	end
  end

  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = "playbook.yml"
  #   # ansible.verbose = "vvv"
  # end
end
